name: Update README with W&B Leaderboard

on:
  workflow_dispatch:
  workflow_run:
    workflows: ["Run W&B Sweep (PySpark Avazu)"]
    types:
      - completed

jobs:
  update-readme:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Login to W&B
        env:
          WANDB_API_KEY: ${{ secrets.WANDB_API_KEY }}
        run: |
          python - << 'PY'
import os, wandb
assert os.getenv("WANDB_API_KEY"), "WANDB_API_KEY not set"
wandb.login(key=os.environ["WANDB_API_KEY"])
print("Logged into W&B")
PY

      - name: Build leaderboard CSV from W&B
        env:
          WANDB_ENTITY: ${{ secrets.WANDB_ENTITY }}
          WANDB_PROJECT: ${{ secrets.WANDB_PROJECT }}
        run: |
          python leaderboard/build_leaderboard.py --entity "$WANDB_ENTITY" --project "$WANDB_PROJECT" --tag avazu_sweep --out leaderboard/leaderboard.csv

      - name: Insert leaderboard block into README
        env:
          WANDB_ENTITY: ${{ secrets.WANDB_ENTITY }}
          WANDB_PROJECT: ${{ secrets.WANDB_PROJECT }}
        run: |
          python tools/insert_leaderboard.py

      - name: Commit README changes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add README.md leaderboard/leaderboard.csv
          git commit -m "Auto-embed W&B leaderboard into README" || echo "Nothing to commit"
          git push